#!/usr/bin/env zsh

DATAFILE="${1}"
ENCFILE="${2}"
ENCPASS="${3}"

[ ${#} -ge 3 ] || {
    echo "SYNTAX | ${0} data_file encrypted_file password"
    exit 1
}

openssl enc -aes-256-cbc -in "${DATAFILE}" -out "${ENCFILE}" -k "${ENCPASS}"
